services:
  mongodb:
    image: 'mongo:7.0.4-jammy'
    container_name: flashcards-mongodb
    ports:
      - '27017:27017'
    volumes:
      - 'flashcards-mongo:/data/db'
    networks:
      - flashcards-network
  authserver:
    image: 'wisskirchenj/flashcardsauth-server:0.0.1-SNAPSHOT'
    container_name: flashcards-authserver
    ports:
      - '8000:8000'
    environment:
      MONGO_HOST: flashcards-mongodb
    depends_on:
      - mongodb
    networks:
      - flashcards-network

volumes:
  flashcards-mongo:

networks:
  flashcards-network:

